server:
  port: 8761

spring:
  application:
    name: expenses-discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    org.springframework.web: DEBUG
